import type { Metadata } from "next";
import { Rubik, UnifrakturMaguntia, Mea_Culpa, Great_Vibes} from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
// import {Providers} from '@/app/[locale]/providers';

const rubik = Rubik({
  subsets: ['latin','latin-ext'],
  // display: 'swap',
  variable: '--font-rubik',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  // display: 'swap',
  variable: "--font-great-vibes",
})

export const metadata: Metadata = {
  title: "Vlamaz | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
      className={`${rubik.className} ${greatVibes.variable}`}
    >
      <body>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
